---
- hosts: all
  gather_facts:
  become: yes
  remote_user: centos
  tasks:
  - name: mout partition in cloud
    script: mount.sh
  - name: reboot affter mount
    reboot:
      reboot_timeout: 300